### ISSUE TITLE
Many errors using the main exemple given

### ISSUE THREAD

**Issue by MatthieuHPP** [Daplie/greenlock-express#108]
Hello,

I am experiencing various error messages and do not see how to go further.
The code I use is coming from the exemple given on github greenlock-express.
Help will be much appreciated
```
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
I had the following warning after installing greenblock-express
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```
I am working with Unbuntu and node 6.X.
I see no folder "acme-challenges" in my "tmp" folder Many thanks for your help.
I tryed to modify the links but it does not work anymore.

```
app.use('/api', router)

const lex = require('greenlock-express').create({
  server: 'staging',
  challenges: { 'http-01': require('le-challenge-fs').create({ webrootPath: '/tmp/acme-challenges' }) },
  store: require('le-store-certbot').create({ webrootPath: '/tmp/acme-challenges' }),
  approveDomains: approveDomains
})

function approveDomains(opts, certs, cb) {
  if (certs) {
    opts.domains = certs.altnames
  }
  else {
    opts.email = 'lepxxxx@gmail.com'   // xxxx to hide true email
    opts.agreeTos = true
  }
  cb(null, { options: opts, certs: certs })
}
require('http').createServer(lex.middleware(require('redirect-https')())).listen(80, function () {
  console.log("Listening for ACME http-01 challenges on", this.address())
})

// handles your app
require('https').createServer(lex.httpsOptions, lex.middleware(app)).listen(443, function () {
  console.log("Listening for ACME tls-sni-01 challenges and serve app on", this.address())
}
```
Modifying port numbers to deal with root users, the compiler works but I do have the following error and the site page is not accessible:

```
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
Listening for ACME http-01 challenges on { address: '::', family: 'IPv6', port: 3000 }
Listening for ACME tls-sni-01 challenges and serve app on { address: '::', family: 'IPv6', port: 1443 }
Build completed in 4.732s

webpack built f2a2e9bb266fe1d87dcc in 4736ms
TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
{ type: 'urn:acme:error:malformed',
  detail: 'DNS name does not have enough labels',
  status: 400 }
ERROR in le-sni-auto:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by insightfuls** [comment]
See comments in the other issue you commented on.

I haven't had experience with it, but I doubt the `fsevents` message is a problem. It's an optional package for Mac users and you shouldn't need it to get Greenlock working fine.

**Comment by MatthieuHPP** [comment]
Insightfuls message : 
I unintentionally deleted my messages in issue#103  so I "copy-paste" the answer I received from Insightfuls. I apologize for this and many thanks to him !

"I don't know how to completely solve your problem, but I can contribute a few things:

    The "loopback should be defined" message is a harmless warning that can be ignored.
    Let's Encrypt will not know which port to fulfill challenges against if you change it; you MUST either use an http-01 challenge on port 80, or a tls-sni-01 challenge on port 443.
    Unless you also want to type the port number in your browser, the app must also be served on port 443 (and you must type https://). If you want to avoid typing either a port or https:// you need to run on port 80, probably redirecting to port 443.
    The example does all this as long as you don't change the ports.
    I could be wrong, but I wouldn't expect Greenlock to automatically create the webroot path. You should have created it yourself already, I think. If you want to avoid this directory entirely (which I suspect you do, as you're putting it in /tmp) then you can use a tls-sni-01 challenge which works without anything in the filesystem. Just use: challenges: { 'tls-sni-01': require('le-challenge-sni').create({}) }
    The

Some thoughts:

    The 'DNS name does not have enough labels' error suggests to me you're trying to register a local hostname or something. Are you using the FQDN (fully qualified domain name) to access the server when you try it in your browser?
    Maybe just hard-code opts.domains in approveDomains for starters, to make sure you're only attempting to register the domain(s) you want."

**Comment by MatthieuHPP** [comment]
I unintentionally deleted my messages in issue#103 so I "copy-paste" the answer I received from Insightfuls. 
I apologize for this and many thanks to him !

I don't know how to completely solve your problem, but I can contribute a few things:

- The "loopback should be defined" message is a harmless warning that can be ignored.
- Let's Encrypt will not know which port to fulfill challenges against if you change it; you MUST either use an http-01 challenge on port 80, or a tls-sni-01 challenge on port 443.
- Unless you also want to type the port number in your browser, the app must also be served on port 443 (and you must type https://). If you want to avoid typing either a port or https:// you need to run on port 80, probably redirecting to port 443.
-  The example does all this as long as you don't change the ports.
-  I could be wrong, but I wouldn't expect Greenlock to automatically create the webroot path. You should have created it yourself already, I think. If you want to avoid this directory entirely (which I suspect you do, as you're putting it in /tmp) then you can use a tls-sni-01 challenge which works without anything in the filesystem. Just use: challenges: { 'tls-sni-01': require('le-challenge-sni').create({}) }

Some thoughts:

- The 'DNS name does not have enough labels' error suggests to me you're trying to register a local hostname or something. Are you using the FQDN (fully qualified domain name) to access the server when you try it in your browser?
- Maybe just hard-code opts.domains in approveDomains for starters, to make sure you're only attempting to register the domain(s) you want.

**Comment by MatthieuHPP** [comment]
Many thanks for your reply Insightfuls : 

> The 'DNS name does not have enough labels' error suggests to me you're trying to register a local hostname or something

I am developing the site locally for now

> I could be wrong, but I wouldn't expect Greenlock to automatically create the webroot path. You should have created it yourself already, I think. If you want to avoid this directory entirely (which I suspect you do, as you're putting it in /tmp) then you can use a tls-sni-01 challenge which works without anything in the filesystem. Just use: challenges: { 'tls-sni-01': require('le-challenge-sni').create({}) }

`/tmp/acme-challenges` was already mentioned in the reference example of greenlock-express. There is a directory tmp at the root on my computer.
I also tried as was suggested in some other issues webrootPath: '~/greenlock/var/acme-challenges' and your suggestion but the problem might comes from elsewhere.

> Unless you also want to type the port number in your browser, the app must also be served on port 443 (and you must type https://). If you want to avoid typing either a port or https:// you need to run on port 80, probably redirecting to port 443.

It works with port 80 & 443 using node with sudo but I cannot access to https://localhost:443 . 

The message of Firefox is the following : 
```

The connection to localhost was interrupted while the page was loading.
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.](url)
```

On the nodejs side the error messages the same as previously mentioned:
```
TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
{ type: 'urn:acme:error:malformed',
  detail: 'DNS name does not have enough labels',
  status: 400 }
ERROR in le-sni-auto:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by insightfuls** [comment]
>> The 'DNS name does not have enough labels' error suggests to me you're trying to register a local hostname or something

> I am developing the site locally for now

Well, there's your problem right there. There's no way Let's Encrypt can validate that you own the domain 'localhost' (or any other local host name). They can only verify you own a domain if the server is actually up and accessible from the Internet at large with a FQDN and DNS is pointing at it (and has propagated fully; Let's Encrypt check DNS from a number of different geographic locations and run by different organisations to ensure a fraudulent registration isn't being made by poisoning one sector of the DNS).

If you want to develop locally, use a self-signed certificate, or a self-signed CA, and override your browser/OS security settings to accept it (i.e. don't use Let's Encrypt at all). Or, put a server live and point DNS at it to get a certificate from Let's Encrypt, then use that certificate locally and put an entry in your hosts file to point at your local server instead of the real one (which you could even take down again, but you'll need it every 90 days to renew the certificate).

**Comment by MatthieuHPP** [comment]
Many thanks for this information !
I will therefore implement greenlock-express a bit later :-).
